### ISSUE TITLE
User Directories skipping

### ISSUE THREAD

**Issue by tryptyx** [johanmeiring/ansible-sftp#4]
Hi

I'm running a playbook based on the example playbook but it is not creating the sub directoreis for the user home directory (incoming, etc...)

`TASK: [SFTP-Server | Create directories] **************************************
skipping: [XXXXXXX.eu-west-1.compute.amazonaws.com]`

example playbook shown below;   Am I missing something?

thanks
paul

```
vars:
    - sftp_users:
      - name: test_user
        password: "$1$salt$XXXXXX"
        authorized: []
        sftp_allow_passwords: true
    - sftp_directories:
      - imports
      - exports 
```
