### ISSUE TITLE
Jailing user inside directory

### ISSUE THREAD

**Issue by Dmitri10** [johanmeiring/ansible-sftp#9]
HI. Will be this feature added for example to /var/www/example.com/uploads?
or what should I do to add it in own task?

**Comment by johanmeiring** [comment]
@Dmitri10 The SFTP users should already be chrooted in the partition + directory that is specified via the `sftp_home_partition` and `sftp_users.x.name` variables.  E.g. given the following configuration:

``` yaml
---
vars:
  sftp_home_partition: /var/sftp
  sftp_users:
    - name: user1
      ...
```

... the user `user1` will be chrooted to `/var/sftp/user1`.

The (original) purpose of this role was to allow user-based SFTP, with chrooting of users to their home directories, not specific other directories.  In the case you mentioned above things could actually get quite hairy in terms of the SFTP config, because chrooted SFTP requires (iirc) that the SFTP root directory belong to the root user, with a "maximum" mode of 750.  In your case this root directory would probably be `/var/www/example.com` ... I'm not sure how well that requirement will play with your http daemon.

**Comment by Dmitri10** [comment]
Thanks for a quick response, but I had some problems with sftp_home_partition (script was crashing) so I used such workaround:
_playbook.yaml_

```
vars:
   - sftp_users:
      - name: importer
        password: ""
        authorized: [./.ssh/importer_id_rsa.pub]
   - sftp_directories:
       - uploads
roles:
   - johanmeiring.sftp-server
```

and after task that deploys site structure added task with

```
  - name: "sftp: set mount"
    raw: sudo mount --bind /var/www/{{ main_domain }}/shared/public/uploads /home/importer/uploads
  - name: "sftp: set chmod"
    raw: sudo chmod g+s /home/importer/uploads
  - name: "sftp: set chown"
    raw: sudo chown -R importer:sftpusers /home/importer/uploads
  - name: "sftp: setfacl"
    raw: sudo setfacl -d -m g::rwx /home/importer/uploads
```

using [this article](http://superuser.com/questions/669690/chrooted-sftp-user-with-write-permissions-to-var-www)
